import { writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

const categories = {
  'Personal Storytelling': [
    'Tell a story about a moment that changed how you see yourself.',
    'Describe the most memorable meal you have ever had and why it stuck with you.',
    'Share a time you laughed so hard you could not stop.',
    'Talk about a place that feels like home, even if it is not where you grew up.',
    'Recall a childhood rule you broke and what happened next.',
    'Describe someone who believed in you before you believed in yourself.',
    'Tell the story of your first big failure and what you learned.',
    'Share a tradition your family has and what it means to you.',
    'Talk about a friendship that surprised you.',
    'Describe a risk you took that paid off.',
    'Share a moment you felt completely out of your depth.',
    'Tell about a time you had to apologize and what made it hard.',
    'Describe the best advice you ever ignored.',
    'Talk about a hobby or interest you picked up later in life.',
    'Share a story about a stranger who impacted your day.',
    'Describe a turning point in a relationship.',
    'Tell about a time you stood up for something you believed in.',
    'Share a memory tied to a specific song or smell.',
    'Describe a moment you felt proud of someone else.',
    'Talk about something you used to be afraid of that no longer scares you.',
  ],
  'Hot Takes': [
    'Share an unpopular opinion about social media.',
    'What is overrated in modern dating culture?',
    'Defend a food combination people judge harshly.',
    'What workplace norm should disappear?',
    'Share a hot take about how people use their phones.',
    'What trend do you think peaked too early?',
    'Defend a movie or show everyone else seems to hate.',
    'What is overrated about being busy all the time?',
    'Share a take on how people give advice online.',
    'What fashion trend should make a comeback—or stay gone?',
    'Defend a habit people call lazy but you find smart.',
    'What is your take on hustle culture?',
    'Share an opinion about how people celebrate birthdays.',
    'What do you think people overthink too much?',
    'Defend a controversial travel opinion you hold.',
    'What take do you have on morning routines?',
    'Share an opinion about group chats.',
    'What do you think is underrated in everyday life?',
    'Defend a parenting or family norm you disagree with.',
    'What belief do you hold that would surprise people who know you?',
  ],
  'Reflection & Growth': [
    'What is one lesson you learned the hard way this year?',
    'Describe a habit you are trying to build and why it matters.',
    'What would you tell your younger self about patience?',
    'Talk about a boundary you are proud of setting.',
    'What does success mean to you right now?',
    'Describe a fear you are actively working through.',
    'What skill do you wish you had started learning sooner?',
    'Talk about a time you chose growth over comfort.',
    'What part of your routine keeps you grounded?',
    'Describe a mistake you would make again because of what it taught you.',
    'What are you currently unlearning?',
    'Talk about a goal that evolved as you pursued it.',
    'What does rest look like for you when you do it well?',
    'Describe a compliment that stayed with you.',
    'What value guides most of your decisions lately?',
    'Talk about a book, podcast, or idea that shifted your thinking.',
    'What are you learning to forgive yourself for?',
    'Describe a season of life you are grateful you went through.',
    'What does confidence look like for you in practice?',
    'Talk about something you want to be remembered for.',
  ],
  'Relationships & Connection': [
    'Describe what makes someone easy to talk to.',
    'Talk about a conversation that deepened a relationship.',
    'What do you appreciate most in a close friend?',
    'Share how you show love or care to people in your life.',
    'Describe a moment you felt truly understood.',
    'What is your love language in everyday actions?',
    'Talk about a relationship that taught you something important.',
    'How do you repair things after a disagreement?',
    'Describe the best text you have received recently.',
    'What makes you feel connected on a hard day?',
    'Talk about someone you admire from afar.',
    'What boundary has improved your relationships?',
    'Describe your ideal way to spend time with people you love.',
    'What do you wish people asked you more often?',
    'Talk about a mentor or role model in your life.',
    'How do you know when someone is trustworthy?',
    'Describe a small gesture that meant a lot to you.',
    'What do you bring to your friendships?',
    'Talk about a time you felt like part of a community.',
    'What relationship advice do you actually follow?',
  ],
  Hypotheticals: [
    'If you could relive one day with no consequences, which day would you pick?',
    'What would you do with an extra hour every morning?',
    'If you had to teach a class tomorrow, what would you teach?',
    'You can only eat one cuisine for a year—what do you choose?',
    'If you woke up famous overnight, what would you be famous for?',
    'What would you do if you had a completely free month?',
    'If you could instantly master one skill, what would it be?',
    'You can travel anywhere tomorrow—where are you going?',
    'If you could have dinner with any fictional character, who and why?',
    'What would your life look like if you moved cities next month?',
    'If you could undo one purchase, what would it be?',
    'You get a billboard in your city—what does it say?',
    'If animals could talk for one day, what would you ask yours?',
    'What would you do with a surprise day off from everything?',
    'If you could live in any decade for a year, which would you choose?',
    'You can only keep three apps on your phone— which stay?',
    'If you started a podcast tomorrow, what is the premise?',
    'What would you do if you had no social media for 30 days?',
    'If you could swap lives with someone for a week, who would it be?',
    'You win a modest lottery—what is the first thing you do?',
  ],
  'Gratitude & Joy': [
    'Name three small things that made you smile this week.',
    'Talk about a person you are grateful for and why.',
    'Describe a simple pleasure you never get tired of.',
    'What is going well in your life that you do not mention enough?',
    'Share a moment of joy you did not expect.',
    'What comfort do you turn to on a tough day?',
    'Describe something beautiful you noticed recently.',
    'Talk about a win—big or small—you want to celebrate.',
    'What are you thankful you said yes to?',
    'Describe a routine that brings you peace.',
    'What made you feel lucky lately?',
    'Talk about a gift—material or not—you cherish.',
    'What part of your daily life do you take for granted?',
    'Describe laughter that healed something in you.',
    'What are you grateful you let go of?',
    'Talk about a meal, walk, or moment that felt perfect.',
    'Who made your life easier recently?',
    'What song or sound instantly lifts your mood?',
    'Describe a place that always makes you feel better.',
    'What are you excited about in the near future?',
  ],
  'Creative & Imagination': [
    'Invent a holiday—what are people celebrating and how?',
    'Describe your life as a movie genre and the opening scene.',
    'If your personality were a color palette, what colors and why?',
    'Create a new ice cream flavor and pitch it.',
    'You are writing a memoir—what is chapter one titled?',
    'Describe a dream job that does not exist yet.',
    'If you had a superpower for everyday life, what would it be?',
    'Invent a robot that helps with one annoying task—what does it do?',
    'Describe the plot of a documentary about your week.',
    'If your home could talk, what would it complain about?',
    'Create a new emoji—what does it look like and mean?',
    'You are curating a museum exhibit about your life—what is on display?',
    'Describe an alternate universe version of yourself.',
    'Invent a coffee shop name and its signature drink.',
    'If you could design a perfect Saturday, hour by hour, what happens?',
    'Describe a world where one everyday inconvenience vanished.',
    'You are on a reality show—what is the challenge?',
    'Create a motto for your current era of life.',
    'If you could rename yourself for a week, what name and why?',
    'Describe a magic door in your city—where does it lead?',
  ],
  'Quick Fire': [
    'Beach or mountains?',
    'Early bird or night owl?',
    'Texts or phone calls?',
    'Plan everything or go with the flow?',
    'Sweet or savory breakfast?',
    'City life or small town?',
    'Books or movies for stories?',
    'Save or spend on experiences?',
    'Coffee or tea—or neither?',
    'One close friend or a big friend group?',
    'Window seat or aisle seat?',
    'Cook at home or eat out?',
    'Music on or silence while working?',
    'Summer or winter?',
    'Dogs, cats, or neither?',
    'Voice memo or written notes?',
    'Last-minute plans or scheduled weeks ahead?',
    'Minimalist space or cozy clutter?',
    'Podcast or playlist on a walk?',
    'One year abroad or one year staying put?',
  ],
}

let globalNum = 0
const lines = ['# Speaking Prompt Library', '', "Today's Bit — 160 daily speaking prompts", '']

for (const [category, prompts] of Object.entries(categories)) {
  lines.push(`## ${category}`, '')
  prompts.forEach((text, i) => {
    globalNum += 1
    lines.push(`${i + 1}. ${text}`)
  })
  lines.push('')
}

const md = lines.join('\n')
writeFileSync(join(root, 'speaking_prompt_library.md'), md, 'utf8')
console.log(`Wrote ${globalNum} prompts to speaking_prompt_library.md`)
